### ISSUE TITLE
在调用空间列表接口时Workspace没有无参构造报错，修改之后可以了

### ISSUE THREAD

**Issue by lcz1993** [coze-dev/coze-java#13]
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Workspace {
    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("icon_url")
    private String iconUrl;

    @JsonProperty("role_type")
    private WorkspaceRoleType roleType;

    @JsonProperty("workspace_type")
    private WorkspaceType workspaceType;

}

**Comment by chyroc** [comment]
Can you please submit a PR to fix this issue?

**Comment by lcz1993** [comment]
已提

**Comment by chyroc** [comment]
没看到
